Update CMake configuration to allow not using Conan and installing the library
brycelelbach/wg21_p2300_std_execution pull request #526
Opened 2022-07-08 10:09 UTC by msimberg

The two primary goals for this PR are:
1. Allowing building without Conan.
2. Allowing installation of the library (headers and CMake configuration files).

For 1. I've added a CMake option `P2300_ENABLE_CONAN` which is on by default to keep the setup working as before for those of you who are using Conan. However, as I don't use Conan myself I'd be grateful if someone who does use it could check that I'm not breaking anything. At least the CI still works, but I don't know how comprehensively it tests the Conan stuff. @paulbendixen I'm pinging you since you've recently made changes to the Conan integration.

The background for this is that I'd like to add a P2300 package to spack (https://github.com/spack/spack), and the Conan integration is unnecessary there.

Minor related changes in this PR:
- Adds CMake options to disable tests and examples. They are on by default.
- Removes the `-dev` suffix from the project name. I'm happy to revert this if you prefer to have it there, but the CMake target namespace should correspond to the project name, and the exported target should in that case be `P2300-dev::P2300`.
- I'm now always setting the version based on the revision in `std_execution.bs` similarly to how it's done in `conanfile.py`, i.e. R6 becomes 0.6.0. This allows the version to be set correctly even when the Conan integration is disabled.
- Removes an unnecessary (I think) target alias. Or is this required for the Conan setup?
- Moves executable-specific flags to a separate `INTERFACE` target. Flags like `-Wall`, `-Wno-non-template-friend`, `-ftemplate-backtrace-limit=0`, and `-fcolor-diagnostics` should not be forced on consumers of the library, but only be set for tests and examples.
- Fix `message(ERROR ...)` to `message(FATAL_ERROR ...)`. The former just prints a literal `ERROR`.

2022-09-01 09:25 UTC, msimberg commented
I was too slow to comment on #590 but really happy to see that it was merged. I've rebased this on main and left changes that I think would still be useful to have in the CMake setup. In no particular order:

- Parse the version number from `std_execution.bs` as is done in the `conanfile.py`
- Don't set `CMAKE_CXX_STANDARD`. This is unnecessary in my understanding and already taken care of by `cxx_std_20`. The user is still free to set `CMAKE_CXX_STANDARD` to 20 or higher if they wish, but it doesn't _need_ to be set.
- Use `CMAKE_INSTALL_INCLUDEDIR` in the `INSTALL_INTERFACE` to be consistent with the install command later on.
- Move "convenience" flags to only be applied on the tests/executables. They should not be applied to depending projects. The only flag that has to be in the target interface is `-fcoroutines`.

@trxcllnt I'd be grateful for your comments on this since you made #590.

2022-09-01 16:01 UTC, trxcllnt commented
@msimberg thanks for rebasing! I saw this PR after the other one was merged, and I liked all the things you added. I'll review it today.

2022-09-02 00:44 UTC, bustercopley commented
@msimberg, the `p2300_executable_flags`, especially `-Wno-non-template-friends`, would be nice to have for compiling the examples, as well as the tests. Also, `$<BOOL:$<CXX_COMPILER_ID:GNU>>` could be expressed more simply as `$<CXX_COMPILER_ID:GNU>`, which is the same boolean value.

2022-09-02 00:53 UTC, trxcllnt commented on CMakeLists.txt
> +                       -fcoroutines>
```suggestion
                       $<$<CXX_COMPILER_ID:GNU>:-fcoroutines>
```

2022-09-02 00:58 UTC, trxcllnt commented on CMakeLists.txt
> +                       -fdiagnostics-color=always>
```cmake
$<$<CXX_COMPILER_ID:GNU>:-fdiagnostics-color=always>
```

2022-09-02 01:01 UTC, trxcllnt commented on CMakeLists.txt
> +                           $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
:+1: woops, forgot to update this :sweat_smile:

2022-09-02 01:01 UTC, trxcllnt commented on CMakeLists.txt
> +                       -Wno-non-template-friend>
```cmake
$<$<CXX_COMPILER_ID:GNU>:-Wno-non-template-friend>
```

2022-09-02 01:04 UTC, trxcllnt approved these changes
Looks good to me :+1:. Made a few small suggestions on the lines @bustercopley mentioned.

2022-09-02 01:19 UTC, bustercopley requested changes
I suggest this extra change as part of the "Set only required compiler flags on main p2300 CMake target, the rest only on tests and examples" commit.
```diff
@@ -211,7 +205,7 @@ catch_discover_tests(test.P2300)
 # Set up examples
 function(def_example target sourceFile)
     add_executable(${target} ${sourceFile})
-    target_link_libraries(${target} PRIVATE P2300::p2300)
+    target_link_libraries(${target} PRIVATE P2300::p2300 p2300_executable_flags)
 endfunction()
 
 def_example(example.hello_world "examples/hello_world.cpp")
```

Thank you, @msimberg and @trxcllnt. It's great to have a nice install target.

2022-09-02 07:37 UTC, msimberg commented
Thanks @trxcllnt and @bustercopley for having a look. Very good catches! They should be fixed now.

The flags were intended to be on examples, but I forgot... and the use of `$<BOOL` was just me being ignorant.

2022-09-02 17:39 UTC, ericniebler approved these changes

2022-09-02 18:08 UTC, merged