Restore conan packaging ability
brycelelbach/wg21_p2300_std_execution pull request #592
Opened 2022-08-30 22:20 UTC by paulbendixen

Restore the parts that enable building a conan package, without requiring the use of conan to retrieve Catch

Closes #591

2022-08-30 22:23 UTC, paulbendixen commented
@trxcllnt I hope this is agreeable with what you wanted to achieve, building should be possible with conan but it is no longer required (please double check) and creating the conan package of P2300 is still possible.

2022-08-31 00:06 UTC, trxcllnt commented
Sure, having conan is fine with me. I removed it because @ericniebler mentioned it's a common point of failure and we weren't really using it. If others do in fact find it helpful, we should keep it around!

2022-08-31 00:07 UTC, trxcllnt commented on test_package/CMakeLists.txt
> -set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
Any reason not to turn this on automatically?

2022-08-31 00:12 UTC, trxcllnt requested changes
What's happening in `test_package/CMakeLists.txt`? I assumed it was a smoketest to validate `P2300` can be consumed by other CMake projects, but it doesn't seem like it can be built without conan. What am I missing?

2022-08-31 15:59 UTC, trxcllnt approved these changes
Approving after a discussion with @ericniebler.

2022-08-31 22:11 UTC, ericniebler commented
I tried this out locally and (modulo a cmake version check) everything configured, built, and ran just fine without needing to jump through any Conan hoops. :tada:

2022-08-31 22:12 UTC, merged

2022-09-02 19:35 UTC, paulbendixen commented
> What's happening in `test_package/CMakeLists.txt`? I assumed it was a smoketest to validate `P2300` can be consumed by other CMake projects, but it doesn't seem like it can be built without conan. What am I missing?

Almost correct `test_package` is a smoke test for validating the conan package and is generated along with the boiler plate when creating a new project, which is why it doesn't really need to be nice for consumption in CMake.